name: JavaScript CI with npm

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - name: Use Node.js 20.9.0
        uses: actions/setup-node@v4
        with:
          node-version: '20.9.0'
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test:unit
