name: CI

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: 21
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Check Gradle Version
        run: ./gradlew --version
      - name: Clean Build
        run: ./gradlew clean test --info --stacktrace --warning-mode all
